### ISSUE TITLE
[Rule] - no-magic numbers

### ISSUE THREAD

**Issue by goldhand** [hzdg/linter-configs#30]
I know we discussed it but I am reconsidering this one... I think magic numbers should be enforced like so:

`"no-magic-numbers": [2, {"ignore": [-1, 0, 1, 2], "detectObjects": false, "ignoreArrayIndexes": true}],`

We ignore `[-1, 0, 1, 2]` because who wants `const DOUBLE = 2;` in code.

I think it's debatable whether `detectObjects` is true or not. Leaning towards `true`.

**Comment by aamorozov** [comment]
Closing as this was implemented a while ago
