### ISSUE TITLE
 Add exemption for react lifecycle methods to `class-methods-use-this` rule

### ISSUE THREAD

**Issue by lettertwo** [hzdg/linter-configs#31]
When writing a React component class, like,

```jsx
class MyComponent extends Component {
  render() {
    return <div>My Component!</div>;
  }
}
```

You will receive the following eslint error:
```
Expected 'this' to be used by class method 'render'
```

This happens because we're turning [class-methods-use-this](http://eslint.org/docs/rules/class-methods-use-this) on by default as one of our [best practices](https://github.com/hzdg/linter-configs/blob/aa67818f710cc751a5e785517cca27c678fb942c/JavaScript%20(eslint)/eslint-config-hzdg/rules/best-practices.js#L6).

Since React requires lifecycle hooks to be members of the component instance, we will often end up seeing this error when authoring component classes.

We could adopt the [airbnb approach](https://github.com/airbnb/javascript/blob/8468ed842314a5d66816927ba6c35f018035cffc/packages/eslint-config-airbnb/rules/react.js#L22-L33) and exempt the react lifecycle names:

```json
  "rules": {
    "class-methods-use-this": [2, {
      "exceptMethods": [
        "render",
        "getInitialState",
        "getDefaultProps",
        "getChildContext",
        "componentWillMount",
        "componentDidMount",
        "componentWillReceiveProps",
        "shouldComponentUpdate",
        "componentWillUpdate",
        "componentDidUpdate",
        "componentWillUnmount",
      ],
    }],
  }
```

If we do that, I'm not sure if it's best to do so in the location where we enable the rule (best practices), or override the config for this rule as part of the hzdg-react config.

Thoughts? Concerns?

**Comment by lettertwo** [comment]
FWIW, it appears airbnb overrides their own base config for this rule in their react-specific config.

**Comment by johnetrent** [comment]
I'm cool with overriding the rule in the react-specific config.
